#!/bin/bash
#SBATCH -p be-long
#SBATCH -t 72:00:00
#SBATCH -N 1 
#SBATCH --ntasks-per-node 20 
#SBATCH --mem-per-cpu 3200M
#SBATCH -exclusive
#SBATCH -o slurm.%N.%j.out
#SBATCH -e slurm.%N.%j.err
#SBATCH --hint=nomultithread

input_dir='input'
mkdir -p $input_dir
output_dir='output'
mkdir -p $output_dir
simulation_info_file="${output_dir}/simulation_info.txt"

# setup environment
. setup_environment.sh >> ${simulation_info_file}
echo >> ${simulation_info_file}
echo "*****************************************************" >> ${simulation_info_file}

# some MPI related stuff
module load mpi/mvapich2/2.2

# run the job
tstart=$(date +%s)

srun --hint=nomultithread ${ORBIT_ROOT}/bin/pyORBIT pyOrbit.py

tend=$(date +%s)
dt=$(($tend - $tstart))
echo 'total simulation time (s): ' $dt >> ${simulation_info_file}

