#!/bin/bash
cd 1p3evs
./clean_folder.sh &
cd ../1p6evs
./clean_folder.sh &
cd ../1p9evs
./clean_folder.sh &
cd ../2p3evs
./clean_folder.sh &
cd ../2p6evs
./clean_folder.sh &
cd ../SC_1p3evs
./clean_folder.sh &
cd ../SC_1p6evs
./clean_folder.sh &
cd ../SC_1p9evs
./clean_folder.sh &
cd ../SC_2p3evs
./clean_folder.sh &
cd ../SC_2p6evs
./clean_folder.sh &
cd ../
